import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

let calls = [ // TEMPORARY: ADD IN CALLS LATER
    {
        name: "call name 1", // what to do with call name? is this necessary?
        status: "Ongoing", 
        time: "13:01:02",
        location: "Park Village"
    },
    {
        name: "call name 2",
        status: "Completed", 
        time: "15:02:35",
        location: "Ya Muthas House"
    },
]

export default function Home() {
  return (
    <div className={styles.home}>
      <Head>
        <title>AI Responder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.header}>
            <h1 className={styles.title}> Emergencies </h1>
            <div className={styles.line}/>
        </div>
        <div className={styles.callwrapper}>
            {calls.map( (call) => (
                <div className={styles.call}>
                    <h2> {call.name} </h2>
                    <p> Status: <span>{call.status}</span></p>
                    <p> Call Started: <span>{call.time}</span></p>
                    <p> Location: <span>{call.location}</span></p>
                </div>
            ))}
        </div>    
      </main>
    </div>
  )
}
